[package]
name = "syl2381"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
name = "syl2381"
path = "src/lib.rs"

[dependencies]
rmodbus = "0.7.4"
serial = "0.4.0"

[dev-dependencies]
paste = "1.0.14"
